#ifndef WATER_TRANSPORT_GLOBAL_H
#define WATER_TRANSPORT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(WATER_TRANSPORT_LIBRARY)
#define WATER_TRANSPORT_EXPORT Q_DECL_EXPORT
#else
#define WATER_TRANSPORT_EXPORT Q_DECL_IMPORT
#endif

#endif // WATER_TRANSPORT_GLOBAL_H
