#ifndef ZLIB_ADAPTER_PLUGIN_GLOBAL_H
#define ZLIB_ADAPTER_PLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ZLIB_ADAPTER_PLUGIN_LIBRARY)
#define ZLIB_ADAPTER_PLUGIN_EXPORT Q_DECL_EXPORT
#else
#define ZLIB_ADAPTER_PLUGIN_EXPORT Q_DECL_IMPORT
#endif

#endif // ZLIB_ADAPTER_PLUGIN_GLOBAL_H
