#ifndef XML_XSLT_PLUGIN_GLOBAL_H
#define XML_XSLT_PLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(XML_XSLT_PLUGIN_LIBRARY)
#define XML_XSLT_PLUGIN_EXPORT Q_DECL_EXPORT
#else
#define XML_XSLT_PLUGIN_EXPORT Q_DECL_IMPORT
#endif

#endif // XML_XSLT_PLUGIN_GLOBAL_H
